version: "3.9"

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - '5477:5432'
    networks:
      - coinbot

  bot:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    links:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - coinbot

networks:
  coinbot:
    name: coinbot
    driver: bridge